#!/usr/bin/env bash
# Refresh the vendored copy of the design system tokens.
#
# Values live in mateCreations (ui/tokens/*.json, DTCG) and are generated by
# Style Dictionary. They are vendored here rather than pulled as a dependency
# because mateCreations is a local-only repo: a CI runner cloning oikos has no
# way to resolve @matecreations/ui. Vendoring the *generated* file keeps the
# single source of truth intact while leaving oikos buildable by anyone.
#
# Never edit src/lib/mate-tokens.css by hand — edit the JSON upstream and rerun
# this. See mateCreations/DESIGN.md §9.
set -euo pipefail

MATE="${MATECREATIONS:-$HOME/code/personal/mateCreations}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if [ ! -d "$MATE/ui" ]; then
  echo "mateCreations not found at $MATE (set MATECREATIONS to override)" >&2
  exit 1
fi

(cd "$MATE/ui" && node style-dictionary.config.mjs >/dev/null)
cp "$MATE/ui/dist/tokens.css" "$HERE/src/lib/mate-tokens.css"

echo "synced tokens from $MATE"
