#!/bin/bash
export WAYLAND_DISPLAY="${WAYLAND_DISPLAY:-wayland-1}"
export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/1000}"
export SDL_VIDEODRIVER=wayland
exec xemu -full-screen -dvd_path "$1" &> /tmp/xemu.log
