#!/bin/bash
export WAYLAND_DISPLAY="${WAYLAND_DISPLAY:-wayland-1}"
export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/1000}"
export QT_QPA_PLATFORM=wayland
exec duckstation-qt -batch -fullscreen -- "$1" &> /tmp/duckstation.log
